### ISSUE TITLE
ERR_INVALID_ARG_TYPE error while adding the PublicReportingAPI

### ISSUE THREAD

**Issue by troyhugs** [reportportal/agent-js-jasmine#74]
```message: TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
stackTrace: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at Function.from (node:buffer:322:9)
    at RPClient.buildMultiPartStream (/agent/_work/r1/a/_Voyager_QA_Automation/node_modules/@reportportal/client-javascript/lib/report-portal-client.js:687:20)
    at RPClient.getRequestLogWithFile (/agent/_work/r1/a/_Voyager_QA_Automation/node_modules/@reportportal/client-javascript/lib/report-portal-client.js:651:18)
    at requestPromise (/agent/_work/r1/a/_Voyager_QA_Automation/node_modules/@reportportal/client-javascript/lib/report-portal-client.js:639:25)
    at /agent/_work/r1/a/_Voyager_QA_Automation/node_modules/@reportportal/client-javascript/lib/report-portal-client.js:540:17```
     

 ```
 const PublicReportingAPI = require('@reportportal/agent-js-jasmine/lib/publicReportingAPI');
try{PublicReportingAPI.info("Selected reasons =>" + reasons);}
 catch(error){ PublicReportingAPI.error(error)};
 ```

**Comment by tr1ble** [comment]
Hello! I've checked many ways to reproduce this issue, but I didn't get anything. So may be you can give some more details. I need to notice that in your example you need to use `launchInfo` instead of `info` to pass your logs to launch or use `info` in test item to pass it to it (https://github.com/reportportal/agent-js-jasmine#readme). Also you can checkout this [](url)

**Comment by mbryl6** [comment]
Closing this issue due to inactivity.
If this still relevant or any concern remains, please feel free to reopen or create a new issue.
